### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by sjimenez77** [devonfw/js-training#17]
Hi @tszewcow, 

We are getting notifications from GitHub about a vulnerability in this repository. Please, review the project dependencies here https://github.com/devonfw/js-training/network/dependencies and update the one that is causing problems. 

It seems that this vulnerability has just arisen and is appearing in multiple projects. 

Thank you very much.

Best regards,
Santos

**Comment by tszewcow** [comment]
Solved, i deleted phantomjs connected dependencies (since the project was closed due to low interest), updated some other deps end ensured that there is no 'hoek' npm package installed in version lower than 5.0.3.
